{% set name = "marqo" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marqo-{{ version }}.tar.gz
  sha256: cc7a5636e35c12cf06ef13166549224613581fafe62104591091013ad37dbb74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
  run:
    - packaging
    - pydantic <2.0.0
    - python >=3.6
    - requests
    - urllib3

test:
  imports:
    - marqo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marqo-ai/marqo
  doc_url: https://marqo.pages.dev/
  summary: Tensor search for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
