{% set name = "marqo" %}
{% set version = "3.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marqo-{{ version }}.tar.gz
  sha256: a7feb5246d1476d8b1497469814c9d36b15032c16d46bbb4179696f938109e92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - python >=3.7
    - requests
    - urllib3 <2.0.0,>=1.26.0
    - pydantic >=2.0.0
    - typing_extensions >=4.5.0
    - packaging

test:
  imports:
    - marqo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marqo-ai/marqo
  doc_url: https://marqo.pages.dev/
  summary: Tensor search for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
