{% set name = "marqo" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marqo-{{ version }}.tar.gz
  sha256: 854c8586aeb9923ae9b707cf4bebdf332c9e0a6fa96fa89749bded58c03cb77e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools >=42
  run:
    - python >=3.0
    - requests
    - urllib3

test:
  imports:
    - marqo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marqo-ai/marqo
  doc_url: https://marqo.pages.dev/
  summary: Tensor search for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
