{% set name = "marqo" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marqo-{{ version }}.tar.gz
  sha256: 157a4aea5560fb75fb0bc69c3366d7d87ba75c68280216f1ff61490c6c39d9e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
    - setuptools >=42
  run:
    - python >=3.0
    - requests
    - urllib3

test:
  imports:
    - marqo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marqo-ai/marqo
  doc_url: https://marqo.pages.dev/
  summary: Tensor search for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
