schema_version: 1

context:
  name: marqo
  version: "3.18.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/marqo-${{ version }}.tar.gz
  sha256: 4b138104afc2bdf43903be8ccd31bec4dfe7c9664fdefc53537f014b86dd3fec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=42
  run:
    - python >=${{ python_min }}
    - requests
    - urllib3 >=1.26.0
    - pydantic >=2.0.0
    - packaging

tests:
  - python:
      imports:
        - marqo
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Tensor search for humans
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/marqo-ai/marqo
  documentation: https://marqo.pages.dev/

extra:
  recipe-maintainers:
    - thewchan
